doc/JS_FooterFirst.html.template
doc/JS_FooterSecond.html.template
gap/PolygonalComplexes/animating.gd
gap/PolygonalComplexes/animating.gi

New method for the JavaScript function.

New transparency funtion for the JavaScript method.

---

.travis.yml
PackageInfo.g

PR to find out problem in PR #120

Adapt name of NautyTraces-Repository

---

gap/PolygonalComplexes/modification.gi
unit_tests/Test_BorderCases_PolygonalComplex.g
unit_tests/test_main.g

This is a better version of JoinEdges for a list (Issue #78 ) and issues #47, #49, #52.

Tests for Split and Join methods and reorganization of JoinEdges 

---

gap/Paths/paths.gd
gap/Paths/paths.gi

ConcatenationOfPaths

---

gap/PolygonalComplexes/modification.gd
gap/PolygonalComplexes/modification.gi

LimitedJoinBoundaries Issue #102 and NC versions for JoinBoundaries

JoinBoundaries

---

gap/PolygonalComplexes/graphs.gi

Add grape back into the package. This fixes Issue #77 .
Before merging this PR, the PR #131 should be merged (and this PR retested), since some relevant new tests are in there.

Add grape back into the package

---

doc/Image_FourGon.tex
gap/Paths/paths.gd
gap/Paths/paths.gi
gap/PolygonalComplexes/modification.gd
gap/PolygonalComplexes/modification.gi

ShiftCyclicPath

---

unit_tests/test_main.g

Missing test calls

---

doc/Image_FaceGraphTetra.tex
gap/PolygonalComplexes/graphs.gd
gap/PolygonalComplexes/graphs.gi
unit_tests/Test_Graphs.g
unit_tests/test_main.g

Face graphs

---

gap/PolygonalComplexes/graphs.gd
gap/PolygonalComplexes/graphs.gi
unit_tests/Test_Graphs.g

I thought it would make sense to have a symmetric edge digraph like for the face graph. Furthermore, there are some other minor changes.

Changes of edge graph

---

gap/Flags/flags.gd
gap/Flags/flags.gi

Implement of BarycentreOf* and more

---

gap/PolygonalComplexes/modification.gd
gap/PolygonalComplexes/modification.gi

Issue #157
I had no idea of changing the code for the mending methods without making it more complicated. If you have any ideas, please let me know. 
I changed the implementation of method CraterMend so the output is better now. Before that, the output didn't just contain pairs of edges.

CutAndMend Improvement

---

gap/PolygonalComplexes/modification.gd
gap/PolygonalComplexes/modification.gi

JoinBoundary

---

gap/PolygonalComplexes/graphs.gd
gap/PolygonalComplexes/graphs.gi
unit_tests/Test_Graphs.g
unit_tests/test_main.g

The method computes for a given graph all (vertex-faithful) simplicial surfaces that have the given graph as face graph.

AllSurfacesOfGraph

---

gap/PolygonalComplexes/drawing.gd

Issue #59, Issue #58 and some ToDos

DrawSurfaceToTikz Documentation

---

gap/PolygonalComplexes/graphs.gi
gap/PolygonalComplexes/modification.gd

Automorphism

---

gap/PolygonalComplexes/animating.gd
gap/PolygonalComplexes/animating.gi
gap/PolygonalComplexes/animating_images.gd

I added a parameter to the printRecord for the method DrawSurfaceToJavaScript to change the thickness of the edges in the html output file.

Edge thickness parameter for DrawSurfaceToJavaScript

---

read.g
unit_tests/Test_Animating.g
unit_tests/test_main.g

#141 
I didn't test edge cases, since I'm not sure what are possible edge cases here.

tests for animating

---

gap/Flags/flags.gd

I added some examples in flags.gd to make the ToDos

Examples in chapter flags

---

gap/PolygonalComplexes/animating.gd
gap/PolygonalComplexes/animating_images.gd
read.g

I changed the documentation a bit and reorganized the methods.

documentation of animating

---

doc/Image_ProjectivePlane.tex
gap/PolygonalComplexes/properties.gd

I did (resp. removed) some ToDos in properties.gd

Todos in properties

---

gap/PolygonalComplexes/properties.gd
gap/PolygonalComplexes/properties.gi

This functions computes all epimorphic images of a simplicial surface where the corresponding epimorphism is butterfly friendly.

AdmissibleRelationsOfSurface

---

README
gap/PolygonalComplexes/constructors.gd
gap/PolygonalComplexes/constructors.gi

I also did 2 tests of committing and pushing in README.

Added the umbrella tip descriptor for vertexfaithful simplicial surfaces

---

gap/PolygonalComplexes/graphs.gi

A distinction between vertex faithful and non vertex faithful was missing

Corrected case for not vertex faithful

---

gap/PolygonalComplexes/graphs.gd
gap/PolygonalComplexes/graphs.gi
unit_tests/Test_Graphs.g

It is enough to consider only chordless and non-separating cycles for the case of vertex-faithful simplicial surfaces.

Added implementation of chordless cycles

---

PackageInfo.g
gap/PolygonalComplexes/animating.gd
gap/PolygonalComplexes/animating.gi

Add a function to return all coordinates saved in a printrecord as a list.

Add ```GetAllVertexCoordinates3DNC``` function

---

gap/PolygonalComplexes/modification.gd
gap/PolygonalComplexes/modification.gi

Adaptation of SubcomplexByFaces to edge-coloured complexes

---

gap/PolygonalComplexes/graphs.gd
unit_tests/Test_Graphs.g

tests changed slightly to work with NautyTraces 0.3

---

gap/ColouredComplexes/isoscelesColouring.gd
gap/ColouredComplexes/isoscelesColouring.gi
gap/ColouredComplexes/isoscelesColouring_images.gd
gap/PolygonalComplexes/properties.gi

VertexCounterByAngle as a counter object

---

gap/ColouredComplexes/edgeColouring.gi
gap/ColouredComplexes/isoscelesColouring.gi
gap/ColouredComplexes/variColouring.gi
gap/Flags/flags.gi
gap/PolygonalComplexes/animating.gi
gap/PolygonalComplexes/graphs.gi
gap/PolygonalComplexes/incidence_geometry.gi
gap/PolygonalComplexes/modification.gi
gap/PolygonalComplexes/properties.gi

Make redispatch consistent

---

PackageInfo.g
doc/SimplicialSurfaces.xml
gap/PolygonalComplexes/constructing_families.gd
gap/PolygonalComplexes/constructing_families.gi
gap/PolygonalComplexes/embedding.gd
gap/PolygonalComplexes/graphs.gi
gap/PolygonalComplexes/properties.gd
init.g
read.g
unit_tests/Test_Graphs.g
unit_tests/test_main.g

Added method for computing re-embeddings on surfaces of non-negative Euler characteristic. Introduction and more content of the chapter will follow.

Added Re-embedding
